version: "3"
services:

  db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: ${PASS_DB}
       POSTGRES_DB: ${NAME_DB}
     ports:
       - ${PORT_DB}:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data

  #  db:
  #    image: postgres:9.6
  #    restart: always
  #    environment:
  #      POSTGRES_PASSWORD: oxefood
  #      POSTGRES_DB: oxefood
  #    ports:
  #      - 5436:5432
  #    volumes:
  #      - ./postgres-data:/bitnami/postgresql/data

    